DROP TABLE Felhasznalo CASCADE CONSTRAINTS;
DROP TABLE Kedvezmeny CASCADE CONSTRAINTS;
DROP TABLE Jegy CASCADE CONSTRAINTS;
DROP TABLE Jarat CASCADE CONSTRAINTS;
DROP TABLE Vonat CASCADE CONSTRAINTS;
DROP TABLE Csatlakozas CASCADE CONSTRAINTS;
DROP TABLE Allomas CASCADE CONSTRAINTS;
DROP TABLE Vasarlas CASCADE CONSTRAINTS;
DROP TABLE Alkalmazott CASCADE CONSTRAINTS;
DROP TABLE Munkabeosztas CASCADE CONSTRAINTS;
DROP TABLE Szabadsag CASCADE CONSTRAINTS;


-- Felhasználó tábla
CREATE TABLE Felhasznalo (
    felhasznalonev VARCHAR2(50),
    jelszo VARCHAR2(256) NOT NULL,
    szuletesi_ido DATE NOT NULL,
    alkalmazott NUMBER(1) CHECK (alkalmazott IN (0,1)),
    administrator NUMBER(1) CHECK (administrator IN (0,1))
);

-- Kedvezmény tábla
CREATE TABLE Kedvezmeny (
    k_azonosito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nev VARCHAR2(100) NOT NULL,
    kedvezmeny_szazalek NUMBER(3) CHECK (kedvezmeny_szazalek BETWEEN 0 AND 100) -- BINARY_FLOAT **volt** a dokumentációba írva ehhez a mezőhöz mielőtt átírtam ott
);

-- Jegy tábla
CREATE TABLE Jegy (
    jegy_azonosito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nev VARCHAR2(100) NOT NULL,
    ar NUMBER NOT NULL,
    felhasznalhato NUMBER(3) CHECK (felhasznalhato BETWEEN 1 AND 365)
);

-- Járat tábla
CREATE TABLE Jarat (
    jarat_azonosito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    indulas TIMESTAMP NOT NULL,
    cs_azonosito NUMBER,
    vonat_azonosito NUMBER
);

-- Vonat tábla
CREATE TABLE Vonat (
    vonat_azonosito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    elso_osztalyu_helyek NUMBER NOT NULL,
    masod_osztalyu_helyek NUMBER NOT NULL
);

-- Csatlakozás tábla
CREATE TABLE Csatlakozas (
    cs_azonosito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    idotartam NUMBER NOT NULL,
    hossz NUMBER NOT NULL,  -- BINARY_FLOAT **volt** a dokumentációba írva ehhez a mezőhöz mielőtt átírtam ott
    elso_a_azonosito NUMBER,
    masodik_a_azonosito NUMBER,
    jarat_azonosito NUMBER
);

-- Állomás tábla
CREATE TABLE Allomas (
    a_azonosito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nev VARCHAR2(100) NOT NULL,
    varos VARCHAR2(100) NOT NULL
);

-- Vásárlás tábla
CREATE TABLE Vasarlas (
    vasarlas_azonosito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    idopont TIMESTAMP NOT NULL,
    felhasznalonev VARCHAR2(50),
    k_azonosito NUMBER,
    jegy_azonosito NUMBER,
    jarat_azonosito NUMBER
);

-- Alkalmazott tábla
CREATE TABLE Alkalmazott (
    a_azonosito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nev VARCHAR2(100) NOT NULL,
    beosztas VARCHAR2(50) NOT NULL,
    oraber NUMBER NOT NULL
);

-- Szabadság tábla
CREATE TABLE Szabadsag (
    sz_azonosito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    mettol DATE NOT NULL,
    meddig DATE NOT NULL,
    a_azonosito NUMBER
);

-- Munkabeosztás tábla
CREATE TABLE Munkabeosztas (
    m_azonosito NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    milyen_nap DATE NOT NULL,
    kezdet NUMBER NOT NULL,
    veg NUMBER NOT NULL,
    a_azonosito NUMBER
);

-- Elsődleges és külső kulcsok hozzáadása
ALTER TABLE Felhasznalo ADD CONSTRAINT pk_felhasznalo PRIMARY KEY (felhasznalonev);
ALTER TABLE Kedvezmeny ADD CONSTRAINT pk_kedvezmeny PRIMARY KEY (k_azonosito);
ALTER TABLE Jegy ADD CONSTRAINT pk_jegy PRIMARY KEY (jegy_azonosito);
ALTER TABLE Jarat ADD CONSTRAINT pk_jarat PRIMARY KEY (jarat_azonosito);
ALTER TABLE Vonat ADD CONSTRAINT pk_vonat PRIMARY KEY (vonat_azonosito);
ALTER TABLE Csatlakozas ADD CONSTRAINT pk_csatlakozas PRIMARY KEY (cs_azonosito);
ALTER TABLE Allomas ADD CONSTRAINT pk_allomas PRIMARY KEY (a_azonosito);
ALTER TABLE Vasarlas ADD CONSTRAINT pk_vasarlas PRIMARY KEY (vasarlas_azonosito);
ALTER TABLE Alkalmazott ADD CONSTRAINT pk_alkalmazott PRIMARY KEY (a_azonosito);
ALTER TABLE Szabadsag ADD CONSTRAINT pk_szabadsag PRIMARY KEY (sz_azonosito);
ALTER TABLE Munkabeosztas ADD CONSTRAINT pk_munkabeosztas PRIMARY KEY (m_azonosito);

-- Külső kulcsok beállítása
ALTER TABLE Jarat ADD CONSTRAINT fk_jarat_csatlakozas FOREIGN KEY (cs_azonosito) REFERENCES Csatlakozas(cs_azonosito) ON DELETE SET NULL;
ALTER TABLE Jarat ADD CONSTRAINT fk_jarat_vonat FOREIGN KEY (vonat_azonosito) REFERENCES Vonat(vonat_azonosito) ON DELETE CASCADE;
ALTER TABLE Csatlakozas ADD CONSTRAINT fk_csatlakozas_allomas1 FOREIGN KEY (elso_a_azonosito) REFERENCES Allomas(a_azonosito) ON DELETE CASCADE;
ALTER TABLE Csatlakozas ADD CONSTRAINT fk_csatlakozas_allomas2 FOREIGN KEY (masodik_a_azonosito) REFERENCES Allomas(a_azonosito) ON DELETE CASCADE;
ALTER TABLE Vasarlas ADD CONSTRAINT fk_vasarlas_felhasznalo FOREIGN KEY (felhasznalonev) REFERENCES Felhasznalo(felhasznalonev) ON DELETE CASCADE;
ALTER TABLE Vasarlas ADD CONSTRAINT fk_vasarlas_kedvezmeny FOREIGN KEY (k_azonosito) REFERENCES Kedvezmeny(k_azonosito) ON DELETE SET NULL;
ALTER TABLE Vasarlas ADD CONSTRAINT fk_vasarlas_jegy FOREIGN KEY (jegy_azonosito) REFERENCES Jegy(jegy_azonosito) ON DELETE CASCADE;
ALTER TABLE Vasarlas ADD CONSTRAINT fk_vasarlas_jarat FOREIGN KEY (jarat_azonosito) REFERENCES Jarat(jarat_azonosito) ON DELETE CASCADE;
ALTER TABLE Szabadsag ADD CONSTRAINT fk_szabadsag_alkalmazott FOREIGN KEY (a_azonosito) REFERENCES Alkalmazott(a_azonosito) ON DELETE CASCADE;
ALTER TABLE Munkabeosztas ADD CONSTRAINT fk_munkabeosztas_alkalmazott FOREIGN KEY (a_azonosito) REFERENCES Alkalmazott(a_azonosito) ON DELETE CASCADE;



-- Triggerek
CREATE OR REPLACE TRIGGER kedvezmeny_trigger
BEFORE INSERT
ON Vasarlas
FOR EACH ROW
DECLARE
    kNev VARCHAR2(100);
    fEv NUMBER;
	fAlk NUMBER;
BEGIN
	SELECT nev INTO kNev FROM Kedvezmeny WHERE k_azonosito = :NEW.k_azonosito;
	SELECT floor(months_between(SYSDATE, CAST(szuletesi_ido AS DATE)) /12) INTO fEv FROM Felhasznalo WHERE felhasznalonev = :NEW.felhasznalonev;
	SELECT alkalmazott INTO fAlk FROM Felhasznalo WHERE felhasznalonev = :NEW.felhasznalonev;
	
    IF kNev = 'Diák' AND fEv > 18 THEN 
        :NEW.k_azonosito := NULL;
    ELSIF kNev = 'Nyugdíjas' AND fEv < 65 THEN
        :NEW.k_azonosito := NULL;
    ELSIF kNev = 'MÁK-ONYF' AND fAlk = 0 THEN 
        :NEW.k_azonosito := NULL;
    END IF;

END;
/


-- Munkabeosztás trigger, Jani

CREATE OR REPLACE TRIGGER beosztas_ellenorzes
BEFORE INSERT OR UPDATE OF kezdet, veg ON munkabeosztas
FOR EACH ROW
DECLARE
    v_szamlalo NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_szamlalo
    FROM munkabeosztas
    WHERE a_azonosito = :NEW.a_azonosito
      AND milyen_nap = :NEW.milyen_nap
      AND m_azonosito != :NEW.m_azonosito
      AND (
          (:NEW.kezdet BETWEEN kezdet AND veg)
          OR (:NEW.veg BETWEEN kezdet AND veg)
          OR (kezdet BETWEEN :NEW.kezdet AND :NEW.veg)
      )
      AND (:NEW.rowid IS NULL OR ROWID != :NEW.ROWID); -- hogy UPDATE-nél ne önmagát nézze

    IF v_szamlalo > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ütköző vagy átfedő beosztás létezik erre az alkalmazottra.');
    END IF;
END;
/







--Szabadság rögzítése tárolt eljárás

CREATE OR REPLACE PROCEDURE Uj_Szabadsag_Rogzitese (
    p_a_azonosito IN NUMBER,
    p_mettol IN DATE,
    p_meddig IN DATE
) AS
    v_count NUMBER;
BEGIN
    -- Ellenőrizzük, van-e átfedés
    SELECT COUNT(*) INTO v_count
    FROM Szabadsag
    WHERE a_azonosito = p_a_azonosito
      AND (
           (p_mettol BETWEEN mettol AND meddig)
        OR (p_meddig BETWEEN mettol AND meddig)
        OR (p_mettol <= mettol AND p_meddig >= meddig)
      );

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Átfedő szabadság már létezik.');
    ELSE
        INSERT INTO Szabadsag (mettol, meddig, a_azonosito)
        VALUES (p_mettol, p_meddig, p_a_azonosito);
    END IF;
END;
/


--Alkalmazottak havi bérének kiszámítása, (Összetett?) lekérdezés

SELECT
  a.a_azonosito,
  a.nev,
  a.oraber,
  EXTRACT(YEAR FROM mb.milyen_nap) AS ev,
  EXTRACT(MONTH FROM mb.milyen_nap) AS honap,
  SUM((mb.veg - mb.kezdet) / 60) AS havi_orak,
  a.oraber * SUM((mb.veg - mb.kezdet) / 60) AS havi_ber
FROM
  Alkalmazott a
JOIN
  Munkabeosztas mb ON a.a_azonosito = mb.a_azonosito
GROUP BY
  a.a_azonosito, a.nev, a.oraber,
  EXTRACT(YEAR FROM mb.milyen_nap),
  EXTRACT(MONTH FROM mb.milyen_nap)
ORDER BY
  ev, honap, a.a_azonosito;

ALTER TRIGGER kedvezmeny_trigger ENABLE;
ALTER TRIGGER beosztas_ellenorzes ENABLE;

COMMIT;

INSERT INTO Felhasznalo VALUES ('Kis Béla', 'kisbela1', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 1, 0);
INSERT INTO Felhasznalo VALUES ('Adminisztrátor Ármin', 'Adminvagyok', TO_DATE('1985-05-15', 'YYYY-MM-DD'), 1, 1);
INSERT INTO Felhasznalo VALUES ('Hát Izsák', 'Vicces00', TO_DATE('1995-07-20', 'YYYY-MM-DD'), 1, 0);
INSERT INTO Felhasznalo VALUES ('Vevő Evelin', 'VE12345', TO_DATE('2000-12-10', 'YYYY-MM-DD'), 0, 0);
INSERT INTO Felhasznalo VALUES ('Adminisztrátor Ádám', 'Testvér2', TO_DATE('1988-04-25', 'YYYY-MM-DD'), 1, 1);
INSERT INTO Felhasznalo VALUES ('Geiger Dániel', 'GEG123', TO_DATE('2003-04-10', 'YYYY-MM-DD'), 0, 0);
INSERT INTO Felhasznalo VALUES ('Macska Alexandra', 'maxaxa343', TO_DATE('2002-10-21', 'YYYY-MM-DD'), 0, 0);
INSERT INTO Felhasznalo VALUES ('Macska Sándor', 'masand434', TO_DATE('2003-10-21', 'YYYY-MM-DD'), 0, 0);
INSERT INTO Felhasznalo VALUES ('Szabó Tamás', 'Goated12312', TO_DATE('1947-08-13', 'YYYY-MM-DD'), 0, 0);
INSERT INTO Felhasznalo VALUES ('Orbán Viktor', 'O1G', TO_DATE('1960-11-11', 'YYYY-MM-DD'), 0, 0);
INSERT INTO Felhasznalo VALUES ('asd', 'scrypt:32768:8:1$W6Un2OWiKJpqYzSe$67f2a346b1ac9d17fa2b06cc56dd37b0a9493af21d81a849adcbc5592b4c335157d9f74644f4eeb3f5e802545f478bbbe2d16160c3f601baeb982da2d00c61a6', TO_DATE('1995-01-10', 'YYYY-MM-DD'), 0, 1);


INSERT INTO Kedvezmeny (nev, kedvezmeny_szazalek) VALUES ('Diák', 50);
INSERT INTO Kedvezmeny (nev, kedvezmeny_szazalek) VALUES ('Nyugdíjas', 50);
INSERT INTO Kedvezmeny (nev, kedvezmeny_szazalek) VALUES ('Családi', 70);
INSERT INTO Kedvezmeny (nev, kedvezmeny_szazalek) VALUES ('Hétvégi', 70);
INSERT INTO Kedvezmeny (nev, kedvezmeny_szazalek) VALUES ('MÁK-ONYF', 10);

INSERT INTO Jegy (nev, ar, felhasznalhato) VALUES ('Másodosztály', 1000, 1);
INSERT INTO Jegy (nev, ar, felhasznalhato) VALUES ('Elsőosztály', 2000, 1);
INSERT INTO Jegy (nev, ar, felhasznalhato) VALUES ('Diák', 500, 1);
INSERT INTO Jegy (nev, ar, felhasznalhato) VALUES ('Nyugdíjas', 500, 1);
INSERT INTO Jegy (nev, ar, felhasznalhato) VALUES ('MÁK-ONYF', 100, 1);


INSERT INTO Vonat (elso_osztalyu_helyek, masod_osztalyu_helyek) VALUES (50, 100);
INSERT INTO Vonat (elso_osztalyu_helyek, masod_osztalyu_helyek) VALUES (60, 120);
INSERT INTO Vonat (elso_osztalyu_helyek, masod_osztalyu_helyek) VALUES (70, 140);
INSERT INTO Vonat (elso_osztalyu_helyek, masod_osztalyu_helyek) VALUES (80, 160);
INSERT INTO Vonat (elso_osztalyu_helyek, masod_osztalyu_helyek) VALUES (90, 180);

INSERT INTO Allomas (nev, varos) VALUES ('Budapest-Keleti', 'Budapest');
INSERT INTO Allomas (nev, varos) VALUES ('Debrecen', 'Debrecen');
INSERT INTO Allomas (nev, varos) VALUES ('Szeged', 'Szeged');
INSERT INTO Allomas (nev, varos) VALUES ('Győr', 'Győr');
INSERT INTO Allomas (nev, varos) VALUES ('Pécs', 'Pécs');

INSERT INTO Csatlakozas (idotartam, hossz, elso_a_azonosito, masodik_a_azonosito, jarat_azonosito) VALUES (30, 10, 1, 2, 1);
INSERT INTO Csatlakozas (idotartam, hossz, elso_a_azonosito, masodik_a_azonosito, jarat_azonosito)  VALUES (45, 20, 3, 4, 2);
INSERT INTO Csatlakozas (idotartam, hossz, elso_a_azonosito, masodik_a_azonosito, jarat_azonosito)  VALUES (60, 30, 5, 1, 3);
INSERT INTO Csatlakozas (idotartam, hossz, elso_a_azonosito, masodik_a_azonosito, jarat_azonosito)  VALUES (75, 40, 2, 3, 4);
INSERT INTO Csatlakozas (idotartam, hossz, elso_a_azonosito, masodik_a_azonosito, jarat_azonosito)  VALUES (90, 50, 4, 5, 5);


INSERT INTO Jarat (indulas, cs_azonosito, vonat_azonosito) VALUES (TO_TIMESTAMP('2025-Jun-20 13:00:10', 'YYYY-Mon-DD HH24:MI:SS', 'NLS_DATE_LANGUAGE=AMERICAN'), 1, 1);
INSERT INTO Jarat (indulas, cs_azonosito, vonat_azonosito) VALUES (TO_TIMESTAMP('2025-Jun-20 14:00:10', 'YYYY-Mon-DD HH24:MI:SS', 'NLS_DATE_LANGUAGE=AMERICAN'), 2, 2);
INSERT INTO Jarat (indulas, cs_azonosito, vonat_azonosito) VALUES (TO_TIMESTAMP('2025-Jun-20 15:00:10', 'YYYY-Mon-DD HH24:MI:SS', 'NLS_DATE_LANGUAGE=AMERICAN'), 3, 3);
INSERT INTO Jarat (indulas, cs_azonosito, vonat_azonosito) VALUES (TO_TIMESTAMP('2025-Jun-20 16:00:10', 'YYYY-Mon-DD HH24:MI:SS', 'NLS_DATE_LANGUAGE=AMERICAN'), 4, 4);
INSERT INTO Jarat (indulas, cs_azonosito, vonat_azonosito) VALUES (TO_TIMESTAMP('2025-Jun-20 17:00:10', 'YYYY-Mon-DD HH24:MI:SS', 'NLS_DATE_LANGUAGE=AMERICAN'), 5, 5);

INSERT INTO Vasarlas (idopont, felhasznalonev, k_azonosito, jegy_azonosito, jarat_azonosito) VALUES (TO_TIMESTAMP('2025-Jun-20 13:00:10', 'YYYY-Mon-DD HH24:MI:SS', 'NLS_DATE_LANGUAGE=AMERICAN'), 'Vevő Evelin', 1, 1, 1);
INSERT INTO Vasarlas (idopont, felhasznalonev, k_azonosito, jegy_azonosito, jarat_azonosito) VALUES (TO_TIMESTAMP('2025-Jun-20 13:10:10', 'YYYY-Mon-DD HH24:MI:SS', 'NLS_DATE_LANGUAGE=AMERICAN'), 'Orbán Viktor', 5, 2, 3);
INSERT INTO Vasarlas (idopont, felhasznalonev, k_azonosito, jegy_azonosito, jarat_azonosito) VALUES (TO_TIMESTAMP('2025-Jun-20 13:20:10', 'YYYY-Mon-DD HH24:MI:SS', 'NLS_DATE_LANGUAGE=AMERICAN'), 'Macska Alexandra', 1, 2, 2);
INSERT INTO Vasarlas (idopont, felhasznalonev, k_azonosito, jegy_azonosito, jarat_azonosito) VALUES (TO_TIMESTAMP('2025-Jun-20 13:30:10', 'YYYY-Mon-DD HH24:MI:SS', 'NLS_DATE_LANGUAGE=AMERICAN'), 'Macska Sándor', 1, 2, 2);
INSERT INTO Vasarlas (idopont, felhasznalonev, k_azonosito, jegy_azonosito, jarat_azonosito) VALUES (TO_TIMESTAMP('2025-Jun-20 13:40:10', 'YYYY-Mon-DD HH24:MI:SS', 'NLS_DATE_LANGUAGE=AMERICAN'), 'Szabó Tamás', 2, 1, 5);



INSERT INTO Alkalmazott (nev, beosztas, oraber) VALUES ('Kovács János', 'Jegyellenőr', 2000);
INSERT INTO Alkalmazott (nev, beosztas, oraber) VALUES ('Nagy Péter', 'Mozdonyvezető', 3000);
INSERT INTO Alkalmazott (nev, beosztas, oraber) VALUES ('Szabó Anna', 'Pénztáros', 1800);
INSERT INTO Alkalmazott (nev, beosztas, oraber) VALUES ('Tóth Béla', 'Karbantartó', 2200);
INSERT INTO Alkalmazott (nev, beosztas, oraber) VALUES ('Varga Erika', 'Diszpécser', 2500);


INSERT INTO Szabadsag (mettol, meddig, a_azonosito) VALUES (TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-04-10', 'YYYY-MM-DD'), 1);
INSERT INTO Szabadsag (mettol, meddig, a_azonosito) VALUES (TO_DATE('2024-04-11', 'YYYY-MM-DD'), TO_DATE('2024-04-20', 'YYYY-MM-DD'), 2);
INSERT INTO Szabadsag (mettol, meddig, a_azonosito) VALUES (TO_DATE('2024-04-21', 'YYYY-MM-DD'), TO_DATE('2024-04-30', 'YYYY-MM-DD'), 3);
INSERT INTO Szabadsag (mettol, meddig, a_azonosito) VALUES (TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2024-05-10', 'YYYY-MM-DD'), 4);
INSERT INTO Szabadsag (mettol, meddig, a_azonosito) VALUES (TO_DATE('2024-05-11', 'YYYY-MM-DD'), TO_DATE('2024-05-20', 'YYYY-MM-DD'), 5);


INSERT INTO Munkabeosztas (milyen_nap, kezdet, veg, a_azonosito) VALUES (DATE '2024-04-06', 480, 960, 1);
INSERT INTO Munkabeosztas (milyen_nap, kezdet, veg, a_azonosito) VALUES (DATE '2024-04-07', 480, 960, 2);
INSERT INTO Munkabeosztas (milyen_nap, kezdet, veg, a_azonosito) VALUES (DATE '2024-04-08', 480, 960, 3);
INSERT INTO Munkabeosztas (milyen_nap, kezdet, veg, a_azonosito) VALUES (DATE '2024-04-09', 480, 960, 4);
INSERT INTO Munkabeosztas (milyen_nap, kezdet, veg, a_azonosito) VALUES (DATE '2024-04-10', 480, 960, 5);
INSERT INTO Munkabeosztas (milyen_nap, kezdet, veg, a_azonosito) VALUES (DATE '2024-04-11', 480, 960, 1);

COMMIT;
